# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from xlators.features.tde.src import tde_pb2 as xlators_dot_features_dot_tde_dot_src_dot_tde__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in xlators/features/tde/src/tde_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TDEServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommunicateWithShard = channel.unary_unary(
                '/tde.TDEService/CommunicateWithShard',
                request_serializer=xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDERequest.SerializeToString,
                response_deserializer=xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDEResponse.FromString,
                _registered_method=True)


class TDEServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommunicateWithShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TDEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommunicateWithShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunicateWithShard,
                    request_deserializer=xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDERequest.FromString,
                    response_serializer=xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDEResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tde.TDEService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tde.TDEService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TDEService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommunicateWithShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tde.TDEService/CommunicateWithShard',
            xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDERequest.SerializeToString,
            xlators_dot_features_dot_tde_dot_src_dot_tde__pb2.TDEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
