# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xlators/features/tde/src/tde.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'xlators/features/tde/src/tde.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"xlators/features/tde/src/tde.proto\x12\x03tde\"-\n\nTDERequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"=\n\x0bTDEResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32I\n\nTDEService\x12;\n\x14\x43ommunicateWithShard\x12\x0f.tde.TDERequest\x1a\x10.tde.TDEResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xlators.features.tde.src.tde_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TDEREQUEST']._serialized_start=43
  _globals['_TDEREQUEST']._serialized_end=88
  _globals['_TDERESPONSE']._serialized_start=90
  _globals['_TDERESPONSE']._serialized_end=151
  _globals['_TDESERVICE']._serialized_start=153
  _globals['_TDESERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
